### ISSUE TITLE
Bottom position

### ISSUE THREAD

**Issue by AndiLeni** [Script47/Toast#11]
Hey, 
I know, this is currently not officially supported, but if someone needs a quick fix for displaying it in the right bottom here are the changes to the css:

```
#toast-container {
    position: sticky;
    z-index: 1055;
    bottom: 0;
}

#toast-wrapper {
    position: fixed;
    bottom: 0;
    right: 0;
    margin: 5px;
}
```

**Comment by Script47** [comment]
@AndiLeni 

There is a plan to handle positioning through classes which can be attached to the container/toast (`.toast-container-position-bottom` with `toast-container-position-right` would plot it top-right etc.).

**Comment by tbategit** [comment]
For bottom center, use:

.toast-container{position:sticky;z-index:1055;bottom:0}.toast-wrapper{position:fixed;bottom:0;left:50%;margin:5px}

**Comment by sagg629** [comment]
Just to complement @tbategit answer...
To show the toast nicely centered, do use 
`transform: translate3d(-50%, 0, 0);` 
on `.toast-wrapper` style.

**Comment by Script47** [comment]
As of v1.0.0 the plugin as top-right, top-left, bottom-right, and bottom-left built into it.
