### ISSUE TITLE
Yellow/warning color hard to read

### ISSUE THREAD

**Issue by jeremiahjp** [Script47/Toast#14]
According to bootstrap 4, the warning color for the toasts has a dark text color with the yellow background.

**Comment by Script47** [comment]
@jeremiahjp 

Thanks for this issue.

Could you provide a source for what your suggesting? If so, I can get around to making this change sometime this weekend.

(not that I don't trust you, it'd save me from having to look around for it)

**Comment by jeremiahjp** [comment]
Sorry for the late response, been busy.

Not that it's a bug, but Bootstrap shows some background color examples with text color on top, and the warning color is shown with black text color.

I think that is more readable than yellow with white.

https://getbootstrap.com/docs/4.3/utilities/colors/#background-color
