### ISSUE TITLE
Exists TypeScript @types for this toast (Script47/Toast)?

### ISSUE THREAD

**Issue by AllanAndrade** [Script47/Toast#17]
When using it on TypeScript, like this: 

```
$.toast({
                title: 'Single message!',
                type: 'error',
                delay: 5000
            });

```
I got the error on NetBeans:

> Property 'toast' does not exist on type 'JQueryStatic'

Then, I tried add "jquery-toast-plugin"  at "TYPES" of my "tsconfig.json", and after this I got the error:

> Argument of type '{ title: string; type: string; delay: number; }' is not assignable to parameter of type 'toastOptions'. Object literal may only specify known properties, and 'title' does not exist in type 'toastOptions'

There are a specific @types for this plugin?

Thanks for any help!

**Comment by Script47** [comment]
Unfortunately, there are no typings for this plugin. If you have any experience in implementing such a thing, I'd happily accept a pull request.
