### ISSUE TITLE
Toast always in left corner

### ISSUE THREAD

**Issue by ognif** [Script47/Toast#18]
I use your Toast script in my page and Iam sure it was before on the right top corner popping up. 
But now it always popup in the left top corner.

I just call:
`function showAlerts(toastTitle, toastContent, toastType){

    $.toast({
        title: toastTitle,
        content: toastContent,
        type: toastType,
        delay: 5000
    });

};`

And I did not change any of your files. Iam confused. Any idea what happen?

**Comment by ognif** [comment]
Additional Info
This happens just on a form login webpage. Always if the toast is shown in the top left corner, there is also a row with white background on top of the page. After toast disappear this white row will also disapear. 
Iam really confused. I complete rebuild the page to its simpelst element and the issue keep stay. On all other pages it is working like expected, only in this login not.

**Comment by Script47** [comment]
@ognif 

Could you please provide live example of this issue?
