### ISSUE TITLE
Toast id duplicates

### ISSUE THREAD

**Issue by crnastena** [Script47/Toast#21]
**What went wrong?**

If you have toasts with delay -1 (that you have to close manually), you can run into issue where toast id generate duplicates.

**What was the console output?**
N/A

**How can we reproduce this bug?**

The Steps to reproduce this behavior:

1. Add 2 toasts with delay of -1.
2. You will now have toast-1 and toast-2 ids.
3. Remove first toast with id toast-1.
4. Add another toast, and id will be toast-2, duplicate.

**What should've happened?**
New toast id should be toast-3.

**Line that generates issue**
var id = 'toast-' + ($('.toast').length + 1),

**Possible solution**

	var toast_wrapper = general_container.children('.toast-container').children('.toast-wrapper');

	var newId = 1;
	var lastToast = $toast_wrapper.children(".toast:last");
	if (lastToast && lastToast.length > 0){
	    var lastId = eval(lastToast[0].id.substring("toast-".length));
	    newId = lastId + 1;
	}

	var id = 'toast-' + newId,

**Miscellaneous (please complete the following information):**

 - Browser - any
 - Bootstrap Version - 4.4.1

**Comment by Script47** [comment]
@crnastena 

Cheers for the report.

This will be addressed in the upcoming v1.0.0.
