### ISSUE TITLE
Position the toasts top-center and bottom-center

### ISSUE THREAD

**Issue by tuebben** [Script47/Toast#25]
Hello,

it would be nice if you could also position the toasts top-center and bottom-center.

Thanks in advance & Greetings ... Peter

**Comment by Script47** [comment]
@tuebben 

If I'm not too busy, I'll try get something added over this weekend.

**Comment by tuebben** [comment]
@Script47 

Thanks for your quick response and the chance to add this feature. I am looking forward to the next version. 😊

**Comment by Script47** [comment]
@tuebben 

Done: https://github.com/Script47/Toast/releases/tag/v1.1.0

**Comment by tuebben** [comment]
@Script47 : Top! 👍

Thanks a lot! 🙏
