### ISSUE TITLE
Is there a way to specify position on specific toast? 

### ISSUE THREAD

**Issue by Greensahil** [Script47/Toast#29]
Looks like you can specify positioning for all of the toasts using toastDefaults. Is there a way to set the position for a specific toast?

I tried this:

```
 $.toast({
                position: 'top-center',
                title: `Default Printer Changed`,
                pauseDelayOnHover: true,
                subtitle: 'Just Now',
                content: `Default printer has been changed to <strong>${data}</strong>`,
                type: 'success',
                delay: 50000
              });
```

but it appears on top-right

**Comment by Script47** [comment]
@Greensahil 

Unfortunately, no, this isn't possible at this moment in time. 

Though maybe not ideal, the only thing you can do for now is to change the position via the defaults before and after the toast is shown.

Maybe in a future iteration I'll have it so you can customise the location per toast.
