### ISSUE TITLE
npm, bower and some version in the library source would be appreciated.

### ISSUE THREAD

**Issue by VictorioBerra** [Script47/Toast#3]

**Comment by Script47** [comment]
@VictorioBerra 

Excellent idea.

I'm thinking of making v1.0.0 official after the completion of:

* Custom styling (rounded toasts, blocky toasts, custom background colours)

and maybe:

* Positioning of the actual toast

then will make an official Github release, add the version to the source and consider npm and bower.

(don't hold me to this!)

**Comment by tip2tail** [comment]
@Script47 

Hey,

Re: Custom styling (rounded toasts, blocky toasts, custom background colours)

Happy to help again and break this work down into a couple of parts.  Have you done any work so far on this yet?  If not I will create a new branch and get to work.

cc:  @VictorioBerra

**Comment by Script47** [comment]
@tip2tail 

I haven't started it yet. 

I'll make a new issue and outline what I had in mind and discuss the best way we can approach this feature.

**Comment by VictorioBerra** [comment]
I highly recommend doing the least amount of work to get it out to package managers. Don't hold off on this part. Even if you have to release `0.1.0` first. Its more important to make the package as easily accessible as possible before you start laying on features.

**Comment by tip2tail** [comment]
I agree @VictorioBerra.  Having this as an npm package would certainly help me to integrate into my frontend build process.

@Script47 - happy to help with the changes you sugest - just let me know :)

**Comment by Script47** [comment]
Folks,

I've never published a package on NPM or any other likewise platform, any ideas how I'd get started?

**Comment by VictorioBerra** [comment]
This is a good article on NPM https://eladnava.com/publishing-your-first-package-to-npm/

It's pretty easy though. You just need need a package.json with the right info and then you run an npm command to publish. Bower is almost the same. 

Another good article https://www.viget.com/articles/publishing-packages-to-npm-and-bower/

**Comment by Script47** [comment]
Before publishing, I want to confirm if this all looks correct:

```
{
  "name": "bs4-toast",
  "version": "0.5.0",
  "description": "Toast - A Bootstrap 4.2+ jQuery plugin for the toast component",
  "main": "dist/toast.min.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Script47/Toast.git"
  },
  "keywords": [
    "bootstrap-4",
    "bootstrap",
    "toast",
    "toast-notifications",
    "snack",
    "jquery-plugin"
  ],
  "author": "Script47",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/Script47/Toast/issues"
  },
  "homepage": "https://github.com/Script47/Toast",
  "dependencies": {
    "bootstrap": ">=4.2.0",
    "jquery": ">=1.9.1"
  }
}
```

**Comment by VictorioBerra** [comment]
That repository.url is wrong I think.

https://docs.npmjs.com/files/package.json#repository

Also, use this project as a reference. It's really similar to yours
https://github.com/makeusabrew/bootbox

**Comment by Script47** [comment]
I find it odd that it generated the Git url incorrectly, that was automated through the publishing process.

Once again, thanks for the information.

**Comment by VictorioBerra** [comment]
Maybe it's fine then. I didn't see the git+ documented but there's a bunch
of undocumented features.

**Comment by Script47** [comment]
@VictorioBerra 

I believe the package should be available on npm as `bs4-toast`, can you test and let me know if you have any issues?

**Comment by VictorioBerra** [comment]
Sure thing. In the future you can do this:

![image](https://user-images.githubusercontent.com/2934507/54567497-093c7f00-49a2-11e9-914f-b6ddde2b7e46.png)

**Comment by Script47** [comment]
Look likes that's that. I'll close this. Feel free to make any new issues regarding npm.
