### ISSUE TITLE
Setting toast id?

### ISSUE THREAD

**Issue by Kiernan-M** [Script47/Toast#30]
In my app I am creating toasts that show the progress of a task rendering on my server.

I am using `$('#toast-'+t).toast('hide');` to later kill the toast once the render is complete and then display a success toast.

For longer running processes, the 'total running count' resets and so I am not always able to hide the right toast.

Is there a way I can set the id of the toast in my js call? Perhaps like this?

`$.toast({
id : jobID,
type: 'info',
title: title,
subtitle: n ....
`

Loving this so much.
Thanks

**Comment by Script47** [comment]
@Kiernan-M this has been added as of 1.2.0.
