### ISSUE TITLE
Add Issue and Pull Request Templates

### ISSUE THREAD

**Issue by draane** [Script47/Toast#9]
I think that pull request and issues templates are really useful (https://github.blog/2016-02-17-issue-and-pull-request-templates/).
For example to specify some steps that have to be done before submitting a pull request, such as minify with the specific minifier.

https://github.com/devspace/awesome-github-templates contains some nice examples.

**Comment by Script47** [comment]
@draane good idea. I'll take a look at the links you've provided (thanks for that) and should have something within then next couple of days.

**Comment by draane** [comment]
@Script47 Nice! I just created a pull request without the template, didn't expect to receive a reply so quickly
